---
title: Agency Jekyll Theme Demo
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
remote_theme: raviriley/agency-jekyll-theme
url: ''
baseurl: "/sakuramilktea"
email: your-email@example.com
description: 'Agency Bootstrap theme converted to a Jekyll theme, plus new features:
  Google Analytics, Markdown support, custom pages, and more!'
author: Your Name
analytics:
  google: 
markdown: kramdown
plugins:
- jekyll-remote-theme
